// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Repairinvoice is the predicate function for repairinvoice builders.
type Repairinvoice func(*sql.Selector)

// Returninvoice is the predicate function for returninvoice builders.
type Returninvoice func(*sql.Selector)

// Statust is the predicate function for statust builders.
type Statust func(*sql.Selector)
