// Code generated by entc, DO NOT EDIT.

package statust

const (
	// Label holds the string label denoting the statust type in the database.
	Label = "statust"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatustname holds the string denoting the statustname field in the database.
	FieldStatustname = "statustname"

	// EdgeStatusts holds the string denoting the statusts edge name in mutations.
	EdgeStatusts = "statusts"

	// Table holds the table name of the statust in the database.
	Table = "statusts"
	// StatustsTable is the table the holds the statusts relation/edge.
	StatustsTable = "returninvoices"
	// StatustsInverseTable is the table name for the Returninvoice entity.
	// It exists in this package in order to avoid circular dependency with the "returninvoice" package.
	StatustsInverseTable = "returninvoices"
	// StatustsColumn is the table column denoting the statusts relation/edge.
	StatustsColumn = "statust_id"
)

// Columns holds all SQL columns for statust fields.
var Columns = []string{
	FieldID,
	FieldStatustname,
}

var (
	// StatustnameValidator is a validator for the "statustname" field. It is called by the builders before save.
	StatustnameValidator func(string) error
)
