// Code generated by entc, DO NOT EDIT.

package statust

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/save-a-gain/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Statustname applies equality check predicate on the "statustname" field. It's identical to StatustnameEQ.
func Statustname(v string) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatustname), v))
	})
}

// StatustnameEQ applies the EQ predicate on the "statustname" field.
func StatustnameEQ(v string) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatustname), v))
	})
}

// StatustnameNEQ applies the NEQ predicate on the "statustname" field.
func StatustnameNEQ(v string) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStatustname), v))
	})
}

// StatustnameIn applies the In predicate on the "statustname" field.
func StatustnameIn(vs ...string) predicate.Statust {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Statust(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStatustname), v...))
	})
}

// StatustnameNotIn applies the NotIn predicate on the "statustname" field.
func StatustnameNotIn(vs ...string) predicate.Statust {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Statust(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStatustname), v...))
	})
}

// StatustnameGT applies the GT predicate on the "statustname" field.
func StatustnameGT(v string) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStatustname), v))
	})
}

// StatustnameGTE applies the GTE predicate on the "statustname" field.
func StatustnameGTE(v string) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStatustname), v))
	})
}

// StatustnameLT applies the LT predicate on the "statustname" field.
func StatustnameLT(v string) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStatustname), v))
	})
}

// StatustnameLTE applies the LTE predicate on the "statustname" field.
func StatustnameLTE(v string) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStatustname), v))
	})
}

// StatustnameContains applies the Contains predicate on the "statustname" field.
func StatustnameContains(v string) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStatustname), v))
	})
}

// StatustnameHasPrefix applies the HasPrefix predicate on the "statustname" field.
func StatustnameHasPrefix(v string) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStatustname), v))
	})
}

// StatustnameHasSuffix applies the HasSuffix predicate on the "statustname" field.
func StatustnameHasSuffix(v string) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStatustname), v))
	})
}

// StatustnameEqualFold applies the EqualFold predicate on the "statustname" field.
func StatustnameEqualFold(v string) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStatustname), v))
	})
}

// StatustnameContainsFold applies the ContainsFold predicate on the "statustname" field.
func StatustnameContainsFold(v string) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStatustname), v))
	})
}

// HasStatusts applies the HasEdge predicate on the "statusts" edge.
func HasStatusts() predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(StatustsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StatustsTable, StatustsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStatustsWith applies the HasEdge predicate on the "statusts" edge with a given conditions (other predicates).
func HasStatustsWith(preds ...predicate.Returninvoice) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(StatustsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StatustsTable, StatustsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Statust) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Statust) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Statust) predicate.Statust {
	return predicate.Statust(func(s *sql.Selector) {
		p(s.Not())
	})
}
