// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/save-a-gain/app/ent/migrate"

	"github.com/save-a-gain/app/ent/employee"
	"github.com/save-a-gain/app/ent/repairinvoice"
	"github.com/save-a-gain/app/ent/returninvoice"
	"github.com/save-a-gain/app/ent/statust"

	"github.com/facebookincubator/ent/dialect"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Employee is the client for interacting with the Employee builders.
	Employee *EmployeeClient
	// Repairinvoice is the client for interacting with the Repairinvoice builders.
	Repairinvoice *RepairinvoiceClient
	// Returninvoice is the client for interacting with the Returninvoice builders.
	Returninvoice *ReturninvoiceClient
	// Statust is the client for interacting with the Statust builders.
	Statust *StatustClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Employee = NewEmployeeClient(c.config)
	c.Repairinvoice = NewRepairinvoiceClient(c.config)
	c.Returninvoice = NewReturninvoiceClient(c.config)
	c.Statust = NewStatustClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Employee:      NewEmployeeClient(cfg),
		Repairinvoice: NewRepairinvoiceClient(cfg),
		Returninvoice: NewReturninvoiceClient(cfg),
		Statust:       NewStatustClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(*sql.Driver).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: &txDriver{tx: tx, drv: c.driver}, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		config:        cfg,
		Employee:      NewEmployeeClient(cfg),
		Repairinvoice: NewRepairinvoiceClient(cfg),
		Returninvoice: NewReturninvoiceClient(cfg),
		Statust:       NewStatustClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Employee.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Employee.Use(hooks...)
	c.Repairinvoice.Use(hooks...)
	c.Returninvoice.Use(hooks...)
	c.Statust.Use(hooks...)
}

// EmployeeClient is a client for the Employee schema.
type EmployeeClient struct {
	config
}

// NewEmployeeClient returns a client for the Employee from the given config.
func NewEmployeeClient(c config) *EmployeeClient {
	return &EmployeeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `employee.Hooks(f(g(h())))`.
func (c *EmployeeClient) Use(hooks ...Hook) {
	c.hooks.Employee = append(c.hooks.Employee, hooks...)
}

// Create returns a create builder for Employee.
func (c *EmployeeClient) Create() *EmployeeCreate {
	mutation := newEmployeeMutation(c.config, OpCreate)
	return &EmployeeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Employee.
func (c *EmployeeClient) Update() *EmployeeUpdate {
	mutation := newEmployeeMutation(c.config, OpUpdate)
	return &EmployeeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EmployeeClient) UpdateOne(e *Employee) *EmployeeUpdateOne {
	mutation := newEmployeeMutation(c.config, OpUpdateOne, withEmployee(e))
	return &EmployeeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EmployeeClient) UpdateOneID(id int) *EmployeeUpdateOne {
	mutation := newEmployeeMutation(c.config, OpUpdateOne, withEmployeeID(id))
	return &EmployeeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Employee.
func (c *EmployeeClient) Delete() *EmployeeDelete {
	mutation := newEmployeeMutation(c.config, OpDelete)
	return &EmployeeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *EmployeeClient) DeleteOne(e *Employee) *EmployeeDeleteOne {
	return c.DeleteOneID(e.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *EmployeeClient) DeleteOneID(id int) *EmployeeDeleteOne {
	builder := c.Delete().Where(employee.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EmployeeDeleteOne{builder}
}

// Create returns a query builder for Employee.
func (c *EmployeeClient) Query() *EmployeeQuery {
	return &EmployeeQuery{config: c.config}
}

// Get returns a Employee entity by its id.
func (c *EmployeeClient) Get(ctx context.Context, id int) (*Employee, error) {
	return c.Query().Where(employee.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EmployeeClient) GetX(ctx context.Context, id int) *Employee {
	e, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return e
}

// QueryEmployees queries the employees edge of a Employee.
func (c *EmployeeClient) QueryEmployees(e *Employee) *ReturninvoiceQuery {
	query := &ReturninvoiceQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := e.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(employee.Table, employee.FieldID, id),
			sqlgraph.To(returninvoice.Table, returninvoice.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, employee.EmployeesTable, employee.EmployeesColumn),
		)
		fromV = sqlgraph.Neighbors(e.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EmployeeClient) Hooks() []Hook {
	return c.hooks.Employee
}

// RepairinvoiceClient is a client for the Repairinvoice schema.
type RepairinvoiceClient struct {
	config
}

// NewRepairinvoiceClient returns a client for the Repairinvoice from the given config.
func NewRepairinvoiceClient(c config) *RepairinvoiceClient {
	return &RepairinvoiceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `repairinvoice.Hooks(f(g(h())))`.
func (c *RepairinvoiceClient) Use(hooks ...Hook) {
	c.hooks.Repairinvoice = append(c.hooks.Repairinvoice, hooks...)
}

// Create returns a create builder for Repairinvoice.
func (c *RepairinvoiceClient) Create() *RepairinvoiceCreate {
	mutation := newRepairinvoiceMutation(c.config, OpCreate)
	return &RepairinvoiceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Repairinvoice.
func (c *RepairinvoiceClient) Update() *RepairinvoiceUpdate {
	mutation := newRepairinvoiceMutation(c.config, OpUpdate)
	return &RepairinvoiceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RepairinvoiceClient) UpdateOne(r *Repairinvoice) *RepairinvoiceUpdateOne {
	mutation := newRepairinvoiceMutation(c.config, OpUpdateOne, withRepairinvoice(r))
	return &RepairinvoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RepairinvoiceClient) UpdateOneID(id int) *RepairinvoiceUpdateOne {
	mutation := newRepairinvoiceMutation(c.config, OpUpdateOne, withRepairinvoiceID(id))
	return &RepairinvoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Repairinvoice.
func (c *RepairinvoiceClient) Delete() *RepairinvoiceDelete {
	mutation := newRepairinvoiceMutation(c.config, OpDelete)
	return &RepairinvoiceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *RepairinvoiceClient) DeleteOne(r *Repairinvoice) *RepairinvoiceDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *RepairinvoiceClient) DeleteOneID(id int) *RepairinvoiceDeleteOne {
	builder := c.Delete().Where(repairinvoice.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RepairinvoiceDeleteOne{builder}
}

// Create returns a query builder for Repairinvoice.
func (c *RepairinvoiceClient) Query() *RepairinvoiceQuery {
	return &RepairinvoiceQuery{config: c.config}
}

// Get returns a Repairinvoice entity by its id.
func (c *RepairinvoiceClient) Get(ctx context.Context, id int) (*Repairinvoice, error) {
	return c.Query().Where(repairinvoice.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RepairinvoiceClient) GetX(ctx context.Context, id int) *Repairinvoice {
	r, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return r
}

// QueryRepairinvoices queries the repairinvoices edge of a Repairinvoice.
func (c *RepairinvoiceClient) QueryRepairinvoices(r *Repairinvoice) *ReturninvoiceQuery {
	query := &ReturninvoiceQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(repairinvoice.Table, repairinvoice.FieldID, id),
			sqlgraph.To(returninvoice.Table, returninvoice.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, repairinvoice.RepairinvoicesTable, repairinvoice.RepairinvoicesColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RepairinvoiceClient) Hooks() []Hook {
	return c.hooks.Repairinvoice
}

// ReturninvoiceClient is a client for the Returninvoice schema.
type ReturninvoiceClient struct {
	config
}

// NewReturninvoiceClient returns a client for the Returninvoice from the given config.
func NewReturninvoiceClient(c config) *ReturninvoiceClient {
	return &ReturninvoiceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `returninvoice.Hooks(f(g(h())))`.
func (c *ReturninvoiceClient) Use(hooks ...Hook) {
	c.hooks.Returninvoice = append(c.hooks.Returninvoice, hooks...)
}

// Create returns a create builder for Returninvoice.
func (c *ReturninvoiceClient) Create() *ReturninvoiceCreate {
	mutation := newReturninvoiceMutation(c.config, OpCreate)
	return &ReturninvoiceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Returninvoice.
func (c *ReturninvoiceClient) Update() *ReturninvoiceUpdate {
	mutation := newReturninvoiceMutation(c.config, OpUpdate)
	return &ReturninvoiceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ReturninvoiceClient) UpdateOne(r *Returninvoice) *ReturninvoiceUpdateOne {
	mutation := newReturninvoiceMutation(c.config, OpUpdateOne, withReturninvoice(r))
	return &ReturninvoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ReturninvoiceClient) UpdateOneID(id int) *ReturninvoiceUpdateOne {
	mutation := newReturninvoiceMutation(c.config, OpUpdateOne, withReturninvoiceID(id))
	return &ReturninvoiceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Returninvoice.
func (c *ReturninvoiceClient) Delete() *ReturninvoiceDelete {
	mutation := newReturninvoiceMutation(c.config, OpDelete)
	return &ReturninvoiceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *ReturninvoiceClient) DeleteOne(r *Returninvoice) *ReturninvoiceDeleteOne {
	return c.DeleteOneID(r.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *ReturninvoiceClient) DeleteOneID(id int) *ReturninvoiceDeleteOne {
	builder := c.Delete().Where(returninvoice.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ReturninvoiceDeleteOne{builder}
}

// Create returns a query builder for Returninvoice.
func (c *ReturninvoiceClient) Query() *ReturninvoiceQuery {
	return &ReturninvoiceQuery{config: c.config}
}

// Get returns a Returninvoice entity by its id.
func (c *ReturninvoiceClient) Get(ctx context.Context, id int) (*Returninvoice, error) {
	return c.Query().Where(returninvoice.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ReturninvoiceClient) GetX(ctx context.Context, id int) *Returninvoice {
	r, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return r
}

// QueryRepairinvoice queries the Repairinvoice edge of a Returninvoice.
func (c *ReturninvoiceClient) QueryRepairinvoice(r *Returninvoice) *RepairinvoiceQuery {
	query := &RepairinvoiceQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(returninvoice.Table, returninvoice.FieldID, id),
			sqlgraph.To(repairinvoice.Table, repairinvoice.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, returninvoice.RepairinvoiceTable, returninvoice.RepairinvoiceColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryEmployee queries the Employee edge of a Returninvoice.
func (c *ReturninvoiceClient) QueryEmployee(r *Returninvoice) *EmployeeQuery {
	query := &EmployeeQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(returninvoice.Table, returninvoice.FieldID, id),
			sqlgraph.To(employee.Table, employee.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, returninvoice.EmployeeTable, returninvoice.EmployeeColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryStatust queries the Statust edge of a Returninvoice.
func (c *ReturninvoiceClient) QueryStatust(r *Returninvoice) *StatustQuery {
	query := &StatustQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := r.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(returninvoice.Table, returninvoice.FieldID, id),
			sqlgraph.To(statust.Table, statust.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, returninvoice.StatustTable, returninvoice.StatustColumn),
		)
		fromV = sqlgraph.Neighbors(r.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ReturninvoiceClient) Hooks() []Hook {
	return c.hooks.Returninvoice
}

// StatustClient is a client for the Statust schema.
type StatustClient struct {
	config
}

// NewStatustClient returns a client for the Statust from the given config.
func NewStatustClient(c config) *StatustClient {
	return &StatustClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `statust.Hooks(f(g(h())))`.
func (c *StatustClient) Use(hooks ...Hook) {
	c.hooks.Statust = append(c.hooks.Statust, hooks...)
}

// Create returns a create builder for Statust.
func (c *StatustClient) Create() *StatustCreate {
	mutation := newStatustMutation(c.config, OpCreate)
	return &StatustCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Statust.
func (c *StatustClient) Update() *StatustUpdate {
	mutation := newStatustMutation(c.config, OpUpdate)
	return &StatustUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StatustClient) UpdateOne(s *Statust) *StatustUpdateOne {
	mutation := newStatustMutation(c.config, OpUpdateOne, withStatust(s))
	return &StatustUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StatustClient) UpdateOneID(id int) *StatustUpdateOne {
	mutation := newStatustMutation(c.config, OpUpdateOne, withStatustID(id))
	return &StatustUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Statust.
func (c *StatustClient) Delete() *StatustDelete {
	mutation := newStatustMutation(c.config, OpDelete)
	return &StatustDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *StatustClient) DeleteOne(s *Statust) *StatustDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *StatustClient) DeleteOneID(id int) *StatustDeleteOne {
	builder := c.Delete().Where(statust.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StatustDeleteOne{builder}
}

// Create returns a query builder for Statust.
func (c *StatustClient) Query() *StatustQuery {
	return &StatustQuery{config: c.config}
}

// Get returns a Statust entity by its id.
func (c *StatustClient) Get(ctx context.Context, id int) (*Statust, error) {
	return c.Query().Where(statust.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StatustClient) GetX(ctx context.Context, id int) *Statust {
	s, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return s
}

// QueryStatusts queries the statusts edge of a Statust.
func (c *StatustClient) QueryStatusts(s *Statust) *ReturninvoiceQuery {
	query := &ReturninvoiceQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(statust.Table, statust.FieldID, id),
			sqlgraph.To(returninvoice.Table, returninvoice.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, statust.StatustsTable, statust.StatustsColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StatustClient) Hooks() []Hook {
	return c.hooks.Statust
}
