// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/save-a-gain/app/ent/predicate"
	"github.com/save-a-gain/app/ent/returninvoice"
	"github.com/save-a-gain/app/ent/statust"
)

// StatustUpdate is the builder for updating Statust entities.
type StatustUpdate struct {
	config
	hooks      []Hook
	mutation   *StatustMutation
	predicates []predicate.Statust
}

// Where adds a new predicate for the builder.
func (su *StatustUpdate) Where(ps ...predicate.Statust) *StatustUpdate {
	su.predicates = append(su.predicates, ps...)
	return su
}

// SetStatustname sets the statustname field.
func (su *StatustUpdate) SetStatustname(s string) *StatustUpdate {
	su.mutation.SetStatustname(s)
	return su
}

// AddStatustIDs adds the statusts edge to Returninvoice by ids.
func (su *StatustUpdate) AddStatustIDs(ids ...int) *StatustUpdate {
	su.mutation.AddStatustIDs(ids...)
	return su
}

// AddStatusts adds the statusts edges to Returninvoice.
func (su *StatustUpdate) AddStatusts(r ...*Returninvoice) *StatustUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return su.AddStatustIDs(ids...)
}

// Mutation returns the StatustMutation object of the builder.
func (su *StatustUpdate) Mutation() *StatustMutation {
	return su.mutation
}

// RemoveStatustIDs removes the statusts edge to Returninvoice by ids.
func (su *StatustUpdate) RemoveStatustIDs(ids ...int) *StatustUpdate {
	su.mutation.RemoveStatustIDs(ids...)
	return su
}

// RemoveStatusts removes statusts edges to Returninvoice.
func (su *StatustUpdate) RemoveStatusts(r ...*Returninvoice) *StatustUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return su.RemoveStatustIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (su *StatustUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := su.mutation.Statustname(); ok {
		if err := statust.StatustnameValidator(v); err != nil {
			return 0, &ValidationError{Name: "statustname", err: fmt.Errorf("ent: validator failed for field \"statustname\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StatustMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *StatustUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StatustUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StatustUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *StatustUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   statust.Table,
			Columns: statust.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: statust.FieldID,
			},
		},
	}
	if ps := su.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Statustname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: statust.FieldStatustname,
		})
	}
	if nodes := su.mutation.RemovedStatustsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statust.StatustsTable,
			Columns: []string{statust.StatustsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: returninvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.StatustsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statust.StatustsTable,
			Columns: []string{statust.StatustsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: returninvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statust.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// StatustUpdateOne is the builder for updating a single Statust entity.
type StatustUpdateOne struct {
	config
	hooks    []Hook
	mutation *StatustMutation
}

// SetStatustname sets the statustname field.
func (suo *StatustUpdateOne) SetStatustname(s string) *StatustUpdateOne {
	suo.mutation.SetStatustname(s)
	return suo
}

// AddStatustIDs adds the statusts edge to Returninvoice by ids.
func (suo *StatustUpdateOne) AddStatustIDs(ids ...int) *StatustUpdateOne {
	suo.mutation.AddStatustIDs(ids...)
	return suo
}

// AddStatusts adds the statusts edges to Returninvoice.
func (suo *StatustUpdateOne) AddStatusts(r ...*Returninvoice) *StatustUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return suo.AddStatustIDs(ids...)
}

// Mutation returns the StatustMutation object of the builder.
func (suo *StatustUpdateOne) Mutation() *StatustMutation {
	return suo.mutation
}

// RemoveStatustIDs removes the statusts edge to Returninvoice by ids.
func (suo *StatustUpdateOne) RemoveStatustIDs(ids ...int) *StatustUpdateOne {
	suo.mutation.RemoveStatustIDs(ids...)
	return suo
}

// RemoveStatusts removes statusts edges to Returninvoice.
func (suo *StatustUpdateOne) RemoveStatusts(r ...*Returninvoice) *StatustUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return suo.RemoveStatustIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (suo *StatustUpdateOne) Save(ctx context.Context) (*Statust, error) {
	if v, ok := suo.mutation.Statustname(); ok {
		if err := statust.StatustnameValidator(v); err != nil {
			return nil, &ValidationError{Name: "statustname", err: fmt.Errorf("ent: validator failed for field \"statustname\": %w", err)}
		}
	}

	var (
		err  error
		node *Statust
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StatustMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StatustUpdateOne) SaveX(ctx context.Context) *Statust {
	s, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return s
}

// Exec executes the query on the entity.
func (suo *StatustUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StatustUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *StatustUpdateOne) sqlSave(ctx context.Context) (s *Statust, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   statust.Table,
			Columns: statust.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: statust.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Statust.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := suo.mutation.Statustname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: statust.FieldStatustname,
		})
	}
	if nodes := suo.mutation.RemovedStatustsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statust.StatustsTable,
			Columns: []string{statust.StatustsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: returninvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.StatustsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statust.StatustsTable,
			Columns: []string{statust.StatustsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: returninvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	s = &Statust{config: suo.config}
	_spec.Assign = s.assignValues
	_spec.ScanValues = s.scanValues()
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statust.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return s, nil
}
