// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/save-a-gain/app/ent/statust"
)

// Statust is the model entity for the Statust schema.
type Statust struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Statustname holds the value of the "statustname" field.
	Statustname string `json:"statustname,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StatustQuery when eager-loading is set.
	Edges StatustEdges `json:"edges"`
}

// StatustEdges holds the relations/edges for other nodes in the graph.
type StatustEdges struct {
	// Statusts holds the value of the statusts edge.
	Statusts []*Returninvoice
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// StatustsOrErr returns the Statusts value or an error if the edge
// was not loaded in eager-loading.
func (e StatustEdges) StatustsOrErr() ([]*Returninvoice, error) {
	if e.loadedTypes[0] {
		return e.Statusts, nil
	}
	return nil, &NotLoadedError{edge: "statusts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Statust) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // statustname
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Statust fields.
func (s *Statust) assignValues(values ...interface{}) error {
	if m, n := len(values), len(statust.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	s.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field statustname", values[0])
	} else if value.Valid {
		s.Statustname = value.String
	}
	return nil
}

// QueryStatusts queries the statusts edge of the Statust.
func (s *Statust) QueryStatusts() *ReturninvoiceQuery {
	return (&StatustClient{config: s.config}).QueryStatusts(s)
}

// Update returns a builder for updating this Statust.
// Note that, you need to call Statust.Unwrap() before calling this method, if this Statust
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Statust) Update() *StatustUpdateOne {
	return (&StatustClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (s *Statust) Unwrap() *Statust {
	tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Statust is not a transactional entity")
	}
	s.config.driver = tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Statust) String() string {
	var builder strings.Builder
	builder.WriteString("Statust(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteString(", statustname=")
	builder.WriteString(s.Statustname)
	builder.WriteByte(')')
	return builder.String()
}

// Statusts is a parsable slice of Statust.
type Statusts []*Statust

func (s Statusts) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
