// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/save-a-gain/app/ent/returninvoice"
	"github.com/save-a-gain/app/ent/statust"
)

// StatustCreate is the builder for creating a Statust entity.
type StatustCreate struct {
	config
	mutation *StatustMutation
	hooks    []Hook
}

// SetStatustname sets the statustname field.
func (sc *StatustCreate) SetStatustname(s string) *StatustCreate {
	sc.mutation.SetStatustname(s)
	return sc
}

// AddStatustIDs adds the statusts edge to Returninvoice by ids.
func (sc *StatustCreate) AddStatustIDs(ids ...int) *StatustCreate {
	sc.mutation.AddStatustIDs(ids...)
	return sc
}

// AddStatusts adds the statusts edges to Returninvoice.
func (sc *StatustCreate) AddStatusts(r ...*Returninvoice) *StatustCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return sc.AddStatustIDs(ids...)
}

// Mutation returns the StatustMutation object of the builder.
func (sc *StatustCreate) Mutation() *StatustMutation {
	return sc.mutation
}

// Save creates the Statust in the database.
func (sc *StatustCreate) Save(ctx context.Context) (*Statust, error) {
	if _, ok := sc.mutation.Statustname(); !ok {
		return nil, &ValidationError{Name: "statustname", err: errors.New("ent: missing required field \"statustname\"")}
	}
	if v, ok := sc.mutation.Statustname(); ok {
		if err := statust.StatustnameValidator(v); err != nil {
			return nil, &ValidationError{Name: "statustname", err: fmt.Errorf("ent: validator failed for field \"statustname\": %w", err)}
		}
	}
	var (
		err  error
		node *Statust
	)
	if len(sc.hooks) == 0 {
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StatustMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StatustCreate) SaveX(ctx context.Context) *Statust {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sc *StatustCreate) sqlSave(ctx context.Context) (*Statust, error) {
	s, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	s.ID = int(id)
	return s, nil
}

func (sc *StatustCreate) createSpec() (*Statust, *sqlgraph.CreateSpec) {
	var (
		s     = &Statust{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: statust.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: statust.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.Statustname(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: statust.FieldStatustname,
		})
		s.Statustname = value
	}
	if nodes := sc.mutation.StatustsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statust.StatustsTable,
			Columns: []string{statust.StatustsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: returninvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return s, _spec
}
