// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// EmployeesColumns holds the columns for the "employees" table.
	EmployeesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "employeename", Type: field.TypeString, Unique: true},
		{Name: "employeeemail", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
	}
	// EmployeesTable holds the schema information for the "employees" table.
	EmployeesTable = &schema.Table{
		Name:        "employees",
		Columns:     EmployeesColumns,
		PrimaryKey:  []*schema.Column{EmployeesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// RepairinvoicesColumns holds the columns for the "repairinvoices" table.
	RepairinvoicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "symptomid", Type: field.TypeInt},
		{Name: "deviceid", Type: field.TypeInt},
		{Name: "userid", Type: field.TypeInt},
		{Name: "statusrepairid", Type: field.TypeInt},
	}
	// RepairinvoicesTable holds the schema information for the "repairinvoices" table.
	RepairinvoicesTable = &schema.Table{
		Name:        "repairinvoices",
		Columns:     RepairinvoicesColumns,
		PrimaryKey:  []*schema.Column{RepairinvoicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// ReturninvoicesColumns holds the columns for the "returninvoices" table.
	ReturninvoicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "addedtime", Type: field.TypeTime},
		{Name: "employee_id", Type: field.TypeInt, Nullable: true},
		{Name: "reparinvoice_id", Type: field.TypeInt, Unique: true, Nullable: true},
		{Name: "statust_id", Type: field.TypeInt, Nullable: true},
	}
	// ReturninvoicesTable holds the schema information for the "returninvoices" table.
	ReturninvoicesTable = &schema.Table{
		Name:       "returninvoices",
		Columns:    ReturninvoicesColumns,
		PrimaryKey: []*schema.Column{ReturninvoicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "returninvoices_employees_employees",
				Columns: []*schema.Column{ReturninvoicesColumns[2]},

				RefColumns: []*schema.Column{EmployeesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "returninvoices_repairinvoices_repairinvoices",
				Columns: []*schema.Column{ReturninvoicesColumns[3]},

				RefColumns: []*schema.Column{RepairinvoicesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "returninvoices_statusts_statusts",
				Columns: []*schema.Column{ReturninvoicesColumns[4]},

				RefColumns: []*schema.Column{StatustsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// StatustsColumns holds the columns for the "statusts" table.
	StatustsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "statustname", Type: field.TypeString, Unique: true},
	}
	// StatustsTable holds the schema information for the "statusts" table.
	StatustsTable = &schema.Table{
		Name:        "statusts",
		Columns:     StatustsColumns,
		PrimaryKey:  []*schema.Column{StatustsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EmployeesTable,
		RepairinvoicesTable,
		ReturninvoicesTable,
		StatustsTable,
	}
)

func init() {
	ReturninvoicesTable.ForeignKeys[0].RefTable = EmployeesTable
	ReturninvoicesTable.ForeignKeys[1].RefTable = RepairinvoicesTable
	ReturninvoicesTable.ForeignKeys[2].RefTable = StatustsTable
}
