/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersReturninvoice
 */
export interface ControllersReturninvoice {
    /**
     * 
     * @type {string}
     * @memberof ControllersReturninvoice
     */
    addedtime?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersReturninvoice
     */
    employee?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersReturninvoice
     */
    repairinvoice?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersReturninvoice
     */
    statust?: number;
}

export function ControllersReturninvoiceFromJSON(json: any): ControllersReturninvoice {
    return ControllersReturninvoiceFromJSONTyped(json, false);
}

export function ControllersReturninvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersReturninvoice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addedtime': !exists(json, 'addedtime') ? undefined : json['addedtime'],
        'employee': !exists(json, 'employee') ? undefined : json['employee'],
        'repairinvoice': !exists(json, 'repairinvoice') ? undefined : json['repairinvoice'],
        'statust': !exists(json, 'statust') ? undefined : json['statust'],
    };
}

export function ControllersReturninvoiceToJSON(value?: ControllersReturninvoice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addedtime': value.addedtime,
        'employee': value.employee,
        'repairinvoice': value.repairinvoice,
        'statust': value.statust,
    };
}


