/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntEmployee,
    EntEmployeeFromJSON,
    EntEmployeeFromJSONTyped,
    EntEmployeeToJSON,
    EntRepairinvoice,
    EntRepairinvoiceFromJSON,
    EntRepairinvoiceFromJSONTyped,
    EntRepairinvoiceToJSON,
    EntStatust,
    EntStatustFromJSON,
    EntStatustFromJSONTyped,
    EntStatustToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntReturninvoiceEdges
 */
export interface EntReturninvoiceEdges {
    /**
     * 
     * @type {EntEmployee}
     * @memberof EntReturninvoiceEdges
     */
    employee?: EntEmployee;
    /**
     * 
     * @type {EntRepairinvoice}
     * @memberof EntReturninvoiceEdges
     */
    repairinvoice?: EntRepairinvoice;
    /**
     * 
     * @type {EntStatust}
     * @memberof EntReturninvoiceEdges
     */
    statust?: EntStatust;
}

export function EntReturninvoiceEdgesFromJSON(json: any): EntReturninvoiceEdges {
    return EntReturninvoiceEdgesFromJSONTyped(json, false);
}

export function EntReturninvoiceEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntReturninvoiceEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'employee': !exists(json, 'Employee') ? undefined : EntEmployeeFromJSON(json['Employee']),
        'repairinvoice': !exists(json, 'Repairinvoice') ? undefined : EntRepairinvoiceFromJSON(json['Repairinvoice']),
        'statust': !exists(json, 'Statust') ? undefined : EntStatustFromJSON(json['Statust']),
    };
}

export function EntReturninvoiceEdgesToJSON(value?: EntReturninvoiceEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'employee': EntEmployeeToJSON(value.employee),
        'repairinvoice': EntRepairinvoiceToJSON(value.repairinvoice),
        'statust': EntStatustToJSON(value.statust),
    };
}


