/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntStatustEdges,
    EntStatustEdgesFromJSON,
    EntStatustEdgesFromJSONTyped,
    EntStatustEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntStatust
 */
export interface EntStatust {
    /**
     * 
     * @type {EntStatustEdges}
     * @memberof EntStatust
     */
    edges?: EntStatustEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntStatust
     */
    id?: number;
    /**
     * Statustname holds the value of the "statustname" field.
     * @type {string}
     * @memberof EntStatust
     */
    statustname?: string;
}

export function EntStatustFromJSON(json: any): EntStatust {
    return EntStatustFromJSONTyped(json, false);
}

export function EntStatustFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntStatust {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntStatustEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'statustname': !exists(json, 'statustname') ? undefined : json['statustname'],
    };
}

export function EntStatustToJSON(value?: EntStatust | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntStatustEdgesToJSON(value.edges),
        'id': value.id,
        'statustname': value.statustname,
    };
}


