// Code generated by entc, DO NOT EDIT.

package returninvoice

const (
	// Label holds the string label denoting the returninvoice type in the database.
	Label = "returninvoice"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAddedtime holds the string denoting the addedtime field in the database.
	FieldAddedtime = "addedtime"

	// EdgeRepairinvoice holds the string denoting the repairinvoice edge name in mutations.
	EdgeRepairinvoice = "Repairinvoice"
	// EdgeEmployee holds the string denoting the employee edge name in mutations.
	EdgeEmployee = "Employee"
	// EdgeStatust holds the string denoting the statust edge name in mutations.
	EdgeStatust = "Statust"

	// Table holds the table name of the returninvoice in the database.
	Table = "returninvoices"
	// RepairinvoiceTable is the table the holds the Repairinvoice relation/edge.
	RepairinvoiceTable = "returninvoices"
	// RepairinvoiceInverseTable is the table name for the Repairinvoice entity.
	// It exists in this package in order to avoid circular dependency with the "repairinvoice" package.
	RepairinvoiceInverseTable = "repairinvoices"
	// RepairinvoiceColumn is the table column denoting the Repairinvoice relation/edge.
	RepairinvoiceColumn = "reparinvoice_id"
	// EmployeeTable is the table the holds the Employee relation/edge.
	EmployeeTable = "returninvoices"
	// EmployeeInverseTable is the table name for the Employee entity.
	// It exists in this package in order to avoid circular dependency with the "employee" package.
	EmployeeInverseTable = "employees"
	// EmployeeColumn is the table column denoting the Employee relation/edge.
	EmployeeColumn = "employee_id"
	// StatustTable is the table the holds the Statust relation/edge.
	StatustTable = "returninvoices"
	// StatustInverseTable is the table name for the Statust entity.
	// It exists in this package in order to avoid circular dependency with the "statust" package.
	StatustInverseTable = "statusts"
	// StatustColumn is the table column denoting the Statust relation/edge.
	StatustColumn = "statust_id"
)

// Columns holds all SQL columns for returninvoice fields.
var Columns = []string{
	FieldID,
	FieldAddedtime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Returninvoice type.
var ForeignKeys = []string{
	"employee_id",
	"reparinvoice_id",
	"statust_id",
}
